#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/colors.txt"

[[ "$BLOCK_BUTTON" == 1 ]] && nm-connection-editor

[[ $(LC_ALL=C nmcli -f wifi -t g s) == 'off' ]] && exit 0

network_name=$(
    LC_ALL=C nmcli -t -f name,device c s -a \
        | grep ":$BLOCK_INSTANCE$" \
        | cut -d':' -f1
)

if [[ -z $network_name ]]; then
    printf "none\n\n$color_warning"
else
    freq=$(iwconfig 2>/dev/null| grep -q 'Frequency:2' && printf '2.4' || printf '5')

    addr=$(
        ip addr show dev "$BLOCK_INSTANCE" 2>/dev/null \
            | grep 'inet ' \
            | sed 's/\s\+inet \([0-9./]\+\).*/\1/'
    )
    [[ -n "$addr" ]] || addr="no IPv4"

    link_quality=$(
        iwconfig 2>/dev/null \
            | grep 'Link Quality' \
            | sed 's/\s\+Link Quality=\([0-9]\+\/[0-9]\+\).*/\1/'
    )

    if [[ $(bc <<< "scale=2; $link_quality < 0.6") == 1 ]]; then
        color="$color_wifi_bad"
    else
        color="$color_wifi_good"
    fi

    net_name_short=$(echo "$network_name" \
        | sed 's/[^a-zA-Z0-9_ \-]//g' \
        | cut -c-15)
    printf '%s %sG %s\n\n%s' "$net_name_short" "$freq" "$addr" "$color"
fi
